/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef __cplusplus
extern "C" {
#endif
GtkWidget* create_gens_window (void);
GtkWidget* create_about (void);
GtkWidget* create_file_selector (void);
GtkWidget* create_game_genie (void);
GtkWidget* create_filters (void);
GtkWidget* create_color_adjust (void);
GtkWidget* create_general_option (void);
GtkWidget* create_controllers_settings (void);
GtkWidget* create_directories_configuration (void);
GtkWidget* create_bios_files (void);
GtkWidget* create_msgbox (void);
#ifdef __cplusplus
}
#endif
